platform: x64

environment:
  PYTHON: "C:\\Python36-x64"
  PYTHON_VERSION: "3.6.3"
  PYTHON_ARCH: "64"
  matrix:
    - compiler: msys2
      MINGW_PREFIX: /mingw64
      MINGW_CHOST: x86_64-w64-mingw32
      MSYS2_ARCH: x86_64
install:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory
  - conan remote add camposs "https://conan.campar.in.tum.de/api/conan/conan-camposs"
test_script:
  - mkdir .build && cd .build
  - conan .. install  --build missing -s compiler=gcc compiler.libcxx=libstdc++11
